tunnel: stefanusadri-tunnel
credentials-file: /home/adri/.cloudflared/stefanusadri-tunnel.json

ingress:
  - hostname: stefanusadri.my.id
    service: https://localhost:443
    originRequest:
      httpHostHeader: stefanusadri.my.id
      noTLSVerify: true
  - service: http_status:404
