version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
    networks:
      - tts-network
    volumes:
      - static-volume:/app/static  # Where Flask generates static files
    # Don't expose port 5000 externally - only for internal nginx access
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/usr/share/nginx/html/static  # Correct nginx static path
    depends_on:
      - app
    networks:
      - tts-network

volumes:
  static-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./static  # Host directory for persistent storage

networks:
  tts-network:
    driver: bridge
